### ISSUE TITLE
The ability to change the locale switcher endpoint

### ISSUE THREAD

**Issue by LoaiDev** [Laravel-Backpack/language-switcher#17] opened 2023-11-22 08:39 UTC
# Feature Request

### What I am trying to achieve

Be able to change the `set-locale` endpoint to something else

### How I see it implemented

- Use the admin prefix in registering the route
- could add an option to disable registering routes so it can be manually added

### What I've already tried to fix it

Try the overwrite the route with the same name but gives an error because 2 routes can't have the same name. since the `language-switcher.locale` route is used directly in the blade file

### Would I be able to work on this myself and submit a PR
I am not sure

my application works by sending /admin requests to the laravel application while anything else is sent to a frontend application. this means that /set-locale is sent to the front end instead. I want to be able to use /admin/set-locale (which I think makes more sense since the language switcher should also use the admin prefix)

**Comment by pxpm** [comment] 2023-11-23 13:17
Hey @LoaiDev thanks for the suggestion. 

This is actually a compromise we took when building this package. Theoretically we wanted to make the language picker available for admins and non-admins (not logged in) users. 

We thought at that time that it's better for the admins to see `https://something.com/set-locale/pt` than regular users seeing `https://something.com/admin/set-locale/pt`.

I get you requirement, I think it makes sense that if you are in `https://something.com/admin/dashboard`, if you change the language it would be in `https://something.com/admin/set-locale/pt`

With that in mind, I think I implemented a solution that provides a lot of flexibility:
- total control of the route, as it's also a good practice to provide when using `named routes` like we do
- also added a sensible configuration that will allow developers to use the language picker at same time in `FE` and `BE` by allowing the route to work with/without the `backpack route prefix`

More info in https://github.com/Laravel-Backpack/language-switcher/pull/18

I will be closing this issue, so that we keep any relevant information regarding implementation (if/when) in the PR thread. If you have some idea that you think would also work, or spotted something that may not work as intended please let us know in that PR, I've asked @promatik to give me his opinion on this matter and his review. 

Thanks for the suggestion @LoaiDev 

🙏

**Closed by pxpm** 2023-11-23 13:17 UTC
